#PBS -N ${PROJECT_ID}_Backup
#PBS -l nodes=1:ppn=1
#PBS -l feature=intel
#PBS -l walltime=12:00:00
#PBS -q iw-shared-6
#PBS -j oe
#PBS -o ../Troubleshooting/Backup.out
#PBS -M ${EMAIL}
#PBS -m abe

cd ~/data/CichlidBowerTracker
echo "Started on `/bin/hostname`"
ssh iw-dm-4 'module load anaconda3; conda activate CichlidBowerTracker; python3 CichlidBowerTracker.py ProjectAnalysis Backup ${PROJECT_ID}'

