#PBS -N ${PROJECT_ID}_DepthAnalysis
#PBS -l nodes=1:ppn=1
#PBS -l feature=intel
#PBS -l walltime=12:00:00
#PBS -q iw-shared-6
#PBS -j oe
#PBS -o ../Troubleshooting/DepthAnalysis.out
#PBS -M ${EMAIL}
#PBS -m abe

cd ~/data/CichlidBowerTracker
echo "Started on `/bin/hostname`"
module load anaconda3
conda activate CichlidBowerTracker
python3 CichlidBowerTracker.py ProjectAnalysis Depth ${PROJECT_ID} -w 1
