#PBS -N ${PROJECT_ID}_MLClusterClassifier
#PBS -l nodes=1:ppn=8:gpus=1:exclusive_process
#PBS -l walltime=6:00:00
#PBS -q biocluster-gpu
#PBS -j oe
#PBS -o ../Troubleshooting/MLClusterClassifier.out
#PBS -M ${EMAIL}
#PBS -m abe

cd ~/data/CichlidBowerTracker
echo "Started on `/bin/hostname`"
module load git-lfs
module load anaconda3
source activate CichlidBowerTracker
python3 CichlidBowerTracker.py ProjectAnalysis MLClassification ${PROJECT_ID} -w 8 -t ${TMPDIR}
