#PBS -N ${PROJECT_ID}_OutfileParsing
#PBS -l nodes=1:ppn=1
#PBS -l feature=intel
#PBS -l walltime=10:00
#PBS -q iw-shared-6
#PBS -j oe
#PBS -o ../Troubleshooting/OutfileParsing.out
#PBS -M ${EMAIL}
#PBS -m abe

cd ~/data/CichlidBowerTracker
echo "Started on `/bin/hostname`"
module load anaconda3
source activate CichlidBowerTracker
python3 CichlidBowerTracker.py ProjectAnalysis Outfiles ${PROJECT_ID} -w 1
