#PBS -N ClusterAnalysis
#PBS -l nodes=1:ppn=8
#PBS -l walltime=12:00:00
#PBS -l pmem=2gb
#PBS -q iw-shared-6
#PBS -j oe
#PBS -o ClusterAnalysis_test3.out
#PBS -m abe
#PBS -t 1-15
#PBS -M tlancaster6@gatech.edu


cd ~/data/CichlidBowerTracker
echo "Started on `/bin/hostname`"
module load anaconda3
source activate CichlidBowerTracker
python CichlidBowerTracker.py ProjectAnalysis Cluster TI2_5_newtray -w 8 -v ${PBS_ARRAYID}
